Repository prebid/prebid-server, pull requests merged in 2018-04, with the labels that each got.

#443 Split Stored Requests from Stored Imps
  config/config_test.go
  config/stored_requests.go
  config/stored_requests_test.go
  docs/developers/stored-requests.md
  endpoints/openrtb2/amp_auction.go
  endpoints/openrtb2/amp_auction_test.go
  endpoints/openrtb2/auction.go
  endpoints/openrtb2/auction_test.go
  pbs_light.go
  pbs_light_test.go
  stored_requests/backends/db_fetcher/fetcher.go
  stored_requests/backends/db_fetcher/fetcher_test.go
  stored_requests/backends/empty_fetcher/fetcher.go
  stored_requests/backends/empty_fetcher/fetcher_test.go
  stored_requests/backends/file_fetcher/fetcher.go
  stored_requests/backends/file_fetcher/fetcher_test.go
  stored_requests/backends/file_fetcher/test/stored_imps/some-imp.json
  stored_requests/backends/file_fetcher/test/stored_requests/1.json
  stored_requests/backends/file_fetcher/test/stored_requests/2.json
  stored_requests/caches/in_memory/lru.go
  stored_requests/caches/in_memory/lru_test.go
  stored_requests/data/by_id/stored_imps/.gitignore
  stored_requests/data/by_id/stored_requests/.gitignore
  stored_requests/fetcher.go
  stored_requests/fetcher_test.go
  stored_requests/multifetcher.go
  stored_requests/multifetcher_test.go
Labels: breaking change - hosts, has docs, needs docs

#449 Made a status response
  pbs_light.go
Labels: in progress

#448 Adding HTTP fetcher
  config/config.go
  config/config_test.go
  config/stored_requests.go
  docs/developers/stored-requests.md
  pbs_light.go
  stored_requests/backends/http_fetcher/fetcher.go
  stored_requests/backends/http_fetcher/fetcher_test.go
Labels: in progress

#451 Various docs updates
  README.md
  docs/developers/add-new-bidder.md
  docs/endpoints/openrtb2/auction.md
Labels: in progress

#450 Adding an HTTP Listener
  config/stored_requests.go
  docs/developers/stored-requests.md
  pbs_light.go
  stored_requests/caches/in_memory/lru.go
  stored_requests/caches/in_memory/lru_test.go
  stored_requests/events/api/api.go
  stored_requests/events/events.go
  stored_requests/events/events_test.go
  stored_requests/events/http/http.go
  stored_requests/events/http/http_test.go
  stored_requests/fetcher.go
  stored_requests/fetcher_test.go
Labels: has docs, needs docs

#453 AMP targeting defaults should included the winning targets
  endpoints/openrtb2/amp_auction.go
  endpoints/openrtb2/amp_auction_test.go
Labels: bug, in progress

#457 Replace Blank Metrics
  pbsmetrics/go_metrics.go
Labels: in progress

#459 Support AMP RTC slot param
  endpoints/openrtb2/amp_auction.go
Labels: in progress

#462 Fix bug in AMP query param handling; add test
  endpoints/openrtb2/amp_auction.go
  endpoints/openrtb2/amp_auction_test.go
Labels: in progress

#456 Incoming connections metrics
  pbs_light.go
  pbsmetrics/go_metrics.go
  pbsmetrics/metrics.go
  server/listener.go
  server/listener_test.go
  server/server.go
  server/server_test.go
Labels: in progress

#461 Moving Stored Request construction
  endpoints/openrtb2/auction_benchmark_test.go
  endpoints/openrtb2/auction_test.go
  pbs_light.go
  pbs_light_test.go
  stored_requests/backends/empty_fetcher/fetcher.go
  stored_requests/backends/empty_fetcher/fetcher_test.go
  stored_requests/backends/http_fetcher/fetcher.go
  stored_requests/backends/http_fetcher/fetcher_test.go
  stored_requests/caches/nil_cache/nil_cache.go
  stored_requests/config/config.go
  stored_requests/config/config_test.go
Labels: in progress

#464 Configure status response
  config/config.go
  docs/endpoints/status.md
  endpoints/status.go
  endpoints/status_test.go
  pbs_light.go
Labels: in progress

#463 Expand in-memory cache to allow unbounded sizes
  config/stored_requests.go
  stored_requests/caches/cachestest/reliable.go
  stored_requests/caches/in_memory/lru_test.go
  stored_requests/caches/memory/cache.go
  stored_requests/caches/memory/cache_test.go
  stored_requests/caches/memory/maps.go
  stored_requests/config/config.go
  stored_requests/events/api/api_test.go
  stored_requests/events/events_test.go
Labels: in progress

#467 Minimize log messages
  adapters/adform/adform.go
  adapters/adtelligent/adtelligent.go
  adapters/appnexus/appnexus.go
  adapters/audienceNetwork/facebook.go
  adapters/bidder.go
  adapters/conversant/conversant.go
  adapters/eplanning/eplanning.go
  adapters/indexExchange/index.go
  adapters/legacy.go
  adapters/lifestreet/lifestreet.go
  adapters/openrtb_util.go
  adapters/openx/openx.go
  adapters/pubmatic/pubmatic.go
  adapters/pulsepoint/pulsepoint.go
  adapters/rubicon/rubicon.go
  adapters/sovrn/sovrn.go
  pbs_light.go
  static/bidder-info/indexExchange.yaml
Labels: in progress

#471 metrics code cleanup and better logging
  exchange/exchange.go
  pbs_light.go
  pbsmetrics/go_metrics.go
Labels: in progress

#472 Fixed some typos; Added sample Stored Request for AMP pages to AMP en…
  docs/developers/stored-requests.md
  docs/endpoints/openrtb2/amp.md
  docs/endpoints/openrtb2/auction.md
Labels: in progress

#474 Update example response on PBS AMP endpoint doc
  docs/endpoints/openrtb2/amp.md
Labels: in progress

#466 Added Go 1.10 to Travis
  .travis.yml
  validate.sh
Labels: in progress

#479 Rubicon adapter support for GDPR
  adapters/rubicon/rubicon.go
Labels: in progress

#484 Made a test useful again
  server/server_test.go
Labels: in progress

#478 Used the pointer error type consistently everywhere
  adapters/adform/adform.go
  adapters/appnexus/appnexus.go
  adapters/audienceNetwork/facebook.go
  adapters/bidder.go
  adapters/conversant/conversant.go
  adapters/pubmatic/pubmatic.go
  pbs_light.go
Labels: in progress

#485 Collect nurl/adm metrics
  exchange/exchange.go
  pbsmetrics/go_metrics.go
  pbsmetrics/go_metrics_test.go
  pbsmetrics/metrics.go
Labels: in progress

#487 Make end-to-end tests documentation-friendly
  docs/endpoints/openrtb2/auction.md
  endpoints/openrtb2/amp_auction_test.go
  endpoints/openrtb2/auction_benchmark_test.go
  endpoints/openrtb2/auction_test.go
  endpoints/openrtb2/sample-requests/valid-whole/aliases.json
  endpoints/openrtb2/sample-requests/valid-whole/app.json
  endpoints/openrtb2/sample-requests/valid-whole/bid-adjustments.json
  endpoints/openrtb2/sample-requests/valid-whole/digitrust.json
  endpoints/openrtb2/sample-requests/valid-whole/exemplary/all-ext.json
  endpoints/openrtb2/sample-requests/valid-whole/exemplary/prebid-test-ad.json
  endpoints/openrtb2/sample-requests/valid-whole/site.json
  endpoints/openrtb2/sample-requests/valid-whole/supplementary/aliased-buyeruids.json
  endpoints/openrtb2/sample-requests/valid-whole/supplementary/aliases.json
  endpoints/openrtb2/sample-requests/valid-whole/supplementary/app.json
  endpoints/openrtb2/sample-requests/valid-whole/supplementary/bid-adjustments.json
  endpoints/openrtb2/sample-requests/valid-whole/supplementary/digitrust.json
  endpoints/openrtb2/sample-requests/valid-whole/supplementary/gdpr-no-consentstring.json
  endpoints/openrtb2/sample-requests/valid-whole/supplementary/gdpr.json
  endpoints/openrtb2/sample-requests/valid-whole/supplementary/site.json
  endpoints/openrtb2/sample-requests/valid-whole/supplementary/timeout.json
  endpoints/openrtb2/sample-requests/valid-whole/supplementary/user.json
  endpoints/openrtb2/sample-requests/valid-whole/timeout.json
  endpoints/openrtb2/sample-requests/valid-whole/user.json
Labels: in progress

#488 Take adm/nurl metrics from the legacy endpoint too
  pbs_light.go
Labels: in progress
