Repository prebid/prebid-server, pull requests merged in 2018-05, with the labels that each got.

#481 Postgres polling EventProducer
  config/stored_requests.go
  config/stored_requests_test.go
  stored_requests/backends/db_fetcher/fetcher.go
  stored_requests/backends/db_fetcher/postgres.go
  stored_requests/backends/db_fetcher/postgres_test.go
  stored_requests/caches/memory/cache.go
  stored_requests/config/config.go
  stored_requests/config/config_test.go
  stored_requests/events/postgres/polling.go
  stored_requests/events/postgres/polling_test.go
  stored_requests/events/postgres/startup.go
  stored_requests/events/postgres/startup_test.go
  stored_requests/fetcher.go
Labels: breaking change - hosts, in progress

#433 Require Bid.CrID properties
  docs/developers/add-new-bidder.md
  exchange/exchange.go
  exchange/validation_test.go
Labels: breaking change - adapters

#502 GDPR-aware Usersyncers
  usersync/adform.go
  usersync/appnexus.go
  usersync/appnexus_test.go
  usersync/conversant.go
  usersync/conversant_test.go
  usersync/indexExchange.go
  usersync/indexExchange_test.go
  usersync/lifestreet.go
  usersync/lifestreet_test.go
  usersync/openx.go
  usersync/openx_test.go
  usersync/pubmatic.go
  usersync/pubmatic_test.go
  usersync/pulsepoint.go
  usersync/pulsepoint_test.go
  usersync/rubicon.go
  usersync/rubicon_test.go
  usersync/sovrn.go
  usersync/sovrn_test.go
  usersync/usersync.go
  usersync/usersync_test.go
Labels: Core Internal APIs

#497 GDPR support for legacy adapters
  adapters/openrtb_util.go
  adapters/openrtb_util_test.go
  exchange/legacy.go
  pbs/pbsrequest.go
Labels: External API impact

#512 GDPR-friendly /cookie_sync
  config/config.go
  docs/endpoints/cookieSync.md
  endpoints/cookie_sync.go
  endpoints/cookie_sync_test.go
  gdpr/gdpr.go
  gdpr/impl_test.go
  gdpr/vendorlist-fetching.go
  gdpr/vendorlist-fetching_test.go
  pbs_light.go
  usersync/usersyncers/syncer.go
Labels: External API impact, has docs, needs docs

#492 Support not sending all bidder keys in targetinng
  docs/endpoints/openrtb2/auction.md
  exchange/exchange.go
  exchange/exchangetest/targeting-only-winners.json
  exchange/targeting.go
  exchange/targeting_test.go
  openrtb_ext/request.go
Labels: External API impact, in progress

#514 Enhances the API used by the http stored request fetcher
  stored_requests/backends/http_fetcher/fetcher.go
  stored_requests/backends/http_fetcher/fetcher_test.go
Labels: breaking change - hosts

#513 GDPR-friendly /setuid
  docs/endpoints/setuid.md
  endpoints/setuid.go
  endpoints/setuid_test.go
  gdpr/gdpr.go
  gdpr/impl.go
  gdpr/impl_test.go
  gdpr/vendorlist-fetching_test.go
  pbs_light.go
  pbsmetrics/go_metrics.go
  pbsmetrics/go_metrics_test.go
  pbsmetrics/metrics.go
Labels: External API impact

#523 Require consent string if gdpr is active
  docs/endpoints/cookieSync.md
  endpoints/cookie_sync.go
  endpoints/cookie_sync_test.go
  endpoints/setuid_test.go
Labels: breaking change - callers

#494 Fixing inventory/visitor data types
  static/bidder-params/rubicon.json
Labels: bug, in progress
