Repository prebid/prebid-server, pull requests merged in 2023-10, with the labels that each got.

#3156 Remove Deprecated Config: Account Blacklist
  account/account.go
  account/account_test.go
  config/config.go
  endpoints/cookie_sync.go
  endpoints/cookie_sync_test.go
  endpoints/events/account_test.go
  endpoints/events/event.go
  endpoints/events/event_test.go
  endpoints/openrtb2/amp_auction.go
  endpoints/openrtb2/amp_auction_test.go
  endpoints/openrtb2/auction.go
  endpoints/openrtb2/auction_benchmark_test.go
  endpoints/openrtb2/auction_test.go
  endpoints/openrtb2/sample-requests/account-required/with-account/required-disabled-acct.json
  endpoints/openrtb2/sample-requests/blacklisted/blacklisted-app-publisher.json
  endpoints/openrtb2/sample-requests/blacklisted/blacklisted-site-publisher.json
  endpoints/openrtb2/test_utils.go
  endpoints/openrtb2/video_auction.go
  endpoints/openrtb2/video_auction_test.go
  endpoints/setuid_test.go
  errortypes/code.go
  errortypes/errortypes.go
Labels: do not port, PBS 2.0

#3155 Remove Config Backwards Compatibility: Account GDPR/CCPA Integration Enabled
  account/account.go
  account/account_test.go
  config/account.go
  config/account_test.go
  metrics/config/metrics.go
  metrics/go_metrics.go
  metrics/go_metrics_test.go
  metrics/metrics.go
  metrics/metrics_mock.go
  metrics/prometheus/prometheus.go
  metrics/prometheus/prometheus_test.go
Labels: do not port, PBS 2.0

#3163 Remove Config Backwards Compatibility: User Sync URL
  config/bidderinfo.go
  config/bidderinfo_test.go
  config/config_test.go
Labels: do not port, PBS 2.0

#3137 lunamedia: update contact info
  static/bidder-info/lunamedia.yaml
Labels: do not port

#3199 Adapter Name Case Insensitive: Events Endpoint
  endpoints/events/event.go
  endpoints/events/event_test.go
Labels: do not port, PBS 2.0

#3196 Adapter Name Case Insensitive: /vtrack endpoint
  endpoints/events/vtrack.go
  endpoints/events/vtrack_test.go
Labels: do not port, PBS 2.0

#3198 Prometheus metrics: bidder name should be in lowercase
  metrics/prometheus/preload.go
  metrics/prometheus/prometheus.go
  metrics/prometheus/prometheus_test.go
  metrics/prometheus/type_conversion.go
Labels: do not port, PBS 2.0

#3209 InfluxDB metrics : bidder name should be in lowercase
  metrics/config/metrics_test.go
  metrics/go_metrics.go
  metrics/go_metrics_test.go
  metrics/metrics.go
  metrics/prometheus/prometheus_test.go
Labels: do not port, PBS 2.0

#3152 Make user.ext.prebid.buyeruids bidder name case insensitive
  endpoints/openrtb2/amp_auction_test.go
  endpoints/openrtb2/auction.go
  endpoints/openrtb2/sample-requests/amp/valid-supplementary/aliased-buyeruids-case-insensitive.json
  endpoints/openrtb2/sample-requests/amp/valid-supplementary/buyeruids-camel-case.json
  endpoints/openrtb2/sample-requests/amp/valid-supplementary/buyeruids-case-insensitive.json
  exchange/exchangetest/buyeruid_case_insensitive.json
  exchange/utils.go
Labels: do not port, PBS 2.0

#3228 Welcome Back: yeahmobi
  adapters/yeahmobi/params_test.go
  adapters/yeahmobi/yeahmobi.go
  adapters/yeahmobi/yeahmobi_test.go
  adapters/yeahmobi/yeahmobitest/exemplary/no-bid.json
  adapters/yeahmobi/yeahmobitest/exemplary/simple-banner.json
  adapters/yeahmobi/yeahmobitest/exemplary/simple-native-1.1.json
  adapters/yeahmobi/yeahmobitest/exemplary/simple-native.json
  adapters/yeahmobi/yeahmobitest/exemplary/simple-video.json
  adapters/yeahmobi/yeahmobitest/supplemental/bad_imp_ext.json
  adapters/yeahmobi/yeahmobitest/supplemental/bad_imp_ext_bidder.json
  adapters/yeahmobi/yeahmobitest/supplemental/bad_response.json
  adapters/yeahmobi/yeahmobitest/supplemental/status_400.json
  adapters/yeahmobi/yeahmobitest/supplemental/status_500.json
  exchange/adapter_builders.go
  exchange/adapter_util.go
  openrtb_ext/bidders.go
  openrtb_ext/imp_yeahmobi.go
  static/bidder-info/yeahmobi.yaml
  static/bidder-params/yeahmobi.json
Labels: PBS 2.0

#3217 Adapter Name Case Insensitive: ext.prebid.multibid
  exchange/exchange.go
  exchange/exchange_test.go
  exchange/exchangetest/multi-bids-mixed-case.json
  exchange/utils.go
Labels: do not port, PBS 2.0

#3189 migrate janet alias to use new pattern
  exchange/adapter_builders.go
  openrtb_ext/bidders.go
  static/bidder-info/janet.yaml
  static/bidder-params/janet.json
Labels: do not port

#3190 migrate pgam alias to use new pattern
  exchange/adapter_builders.go
  openrtb_ext/bidders.go
  static/bidder-info/pgam.yaml
  static/bidder-params/pgam.json
Labels: do not port

#3191 migrate streamkey alias to use new pattern
  exchange/adapter_builders.go
  openrtb_ext/bidders.go
  static/bidder-info/streamkey.yaml
  static/bidder-params/streamkey.json
Labels: do not port

#3192 migrate viewdeos alias to use new pattern
  exchange/adapter_builders.go
  openrtb_ext/bidders.go
  static/bidder-info/viewdeos.yaml
  static/bidder-params/viewdeos.json
Labels: do not port

#3183 migrate limelight aliases to follow new pattern
  exchange/adapter_builders.go
  openrtb_ext/bidders.go
  static/bidder-info/adsyield.yaml
  static/bidder-info/appstock.yaml
  static/bidder-info/evtech.yaml
  static/bidder-info/greedygame.yaml
  static/bidder-info/iionads.yaml
  static/bidder-info/xtrmqb.yaml
  static/bidder-params/adsyield.json
  static/bidder-params/appstock.json
  static/bidder-params/evtech.json
  static/bidder-params/greedygame.json
  static/bidder-params/iionads.json
  static/bidder-params/xtrmqb.json
Labels: do not port

#3184 migrate apacdex aliases to use new pattern
  exchange/adapter_builders.go
  openrtb_ext/bidders.go
  static/bidder-info/quantumdex.yaml
  static/bidder-info/valueimpression.yaml
  static/bidder-params/quantumdex.json
  static/bidder-params/valueimpression.json
Labels: do not port

#3235 Update release workflow to support major version release
  .github/workflows/release.yml
Labels: PBS 2.0

#3244 Restore Hardcoded Alias User Syncs
  static/bidder-info/adform.yaml
  static/bidder-info/quantumdex.yaml
  static/bidder-info/valueimpression.yaml
Labels: do not port, PBS 2.0

#3242 Revert "Remove Adapter: Define Media"
  adapters/definemedia/definemedia.go
  adapters/definemedia/definemedia_test.go
  adapters/definemedia/definemediatest/exemplary/sample-conative-banner.json
  adapters/definemedia/definemediatest/exemplary/sample-conative-native.json
  adapters/definemedia/definemediatest/supplemental/nobid-response.json
  adapters/definemedia/definemediatest/supplemental/nocontent-response.json
  adapters/definemedia/definemediatest/supplemental/status_400.json
  adapters/definemedia/definemediatest/supplemental/status_418.json
  adapters/definemedia/definemediatest/supplemental/unmarshal-error.json
  adapters/definemedia/definemediatest/supplemental/unsupported-type.json
  adapters/definemedia/params_test.go
  exchange/adapter_builders.go
  exchange/adapter_util.go
  openrtb_ext/bidders.go
  openrtb_ext/imp_definemedia.go
  static/bidder-info/definemedia.yaml
  static/bidder-params/definemedia.json
Labels: do not port, PBS 2.0

#3229 Adapter Name Case Insensitive: alternate bidder codes
  exchange/exchangetest/alternate-bidder-codes.json
  exchange/utils.go
  exchange/utils_test.go
  openrtb_ext/alternatebiddercodes.go
  openrtb_ext/alternatebiddercodes_test.go
Labels: do not port, PBS 2.0
