Repository prebid/prebid-server, pull requests merged in 2024-10, with the labels that each got.

#3992 ORTB 2.6: Temporarily remove down convert and make test suite pass
  endpoints/openrtb2/sample-requests/amp/consent-through-query/gdpr-ccpa-through-query.json
  endpoints/openrtb2/sample-requests/amp/consent-through-query/gdpr-legacy-tcf2-consent-through-query.json
  endpoints/openrtb2/sample-requests/amp/consent-through-query/gdpr-tcf1-consent-through-query.json
  endpoints/openrtb2/sample-requests/amp/consent-through-query/gdpr-tcf2-consent-through-query.json
  exchange/exchangetest/ccpa-featureflag-on.json
  exchange/utils.go
  exchange/utils_test.go
  openrtb_ext/request_wrapper.go
  openrtb_ext/request_wrapper_test.go
Labels: do not port

#4002 ORTB 2.6: Push wrapper into prepare user function
  exchange/utils.go
Labels: do not port

#4001 ORTB 2.6: Push wrapper into set legacy from GPP functions
  exchange/utils.go
  exchange/utils_test.go
Labels: do not port

#3999 ORTB 2.6: Pass bidder wrapper into blocked by privacy function
  exchange/utils.go
Labels: do not port

#4004 ORTB 2.6: Harden SetImps to cover larger changes
  openrtb_ext/request_wrapper.go
  openrtb_ext/request_wrapper_test.go
Labels: do not port

#3983 Bump Go version to 1.22 in dev containers config
  .devcontainer/devcontainer.json
Labels: do not port

#3792 Sample: fix prebid js loading bug on sample html page
  sample/001_banner/pbjs.html
Labels: do not port

#3998 ORTB 2.6: Push wrapper into Eidpermissions and ApplyFPD
  exchange/exchangetest/eidpermissions-denied.json
  exchange/exchangetest/firstpartydata-multibidder-user-eids.json
  exchange/exchangetest/firstpartydata-user-eids-req-user-nil.json
  exchange/exchangetest/firstpartydata-user-nileids-req-user-nil.json
  exchange/utils.go
  exchange/utils_test.go
Labels: do not port

#4012 ORTB 2.6: Adds a Regs clone
  exchange/utils.go
  ortb/clone.go
  ortb/clone_test.go
Labels: do not port

#4011 ORTB 2.6: Fix AMP endpoint openrtb2 tests and add AMP upconvert test
  endpoints/openrtb2/amp_auction_test.go
  endpoints/openrtb2/sample-requests/amp/valid-supplementary/ortb-2.5-to-2.6-upconvert.json
Labels: do not port

#4013 ORTB 2.6: Add auction endpoint test and capture validated request
  endpoints/openrtb2/auction_test.go
  endpoints/openrtb2/sample-requests/valid-whole/exemplary/ortb-2.5-to-2.6-upconvert.json
  endpoints/openrtb2/test_utils.go
Labels: do not port

#4010 ORTB 2.6: Test exchange json fixes
  exchange/exchange_test.go
  exchange/exchangetest/ccpa-featureflag-on.json
  exchange/exchangetest/firstpartydata-multibidder-user-eids.json
  exchange/exchangetest/firstpartydata-user-eids-req-user-nil.json
  exchange/exchangetest/multi-bids-different-ortb-versions.json
  exchange/exchangetest/schain-host-and-request.json
  exchange/exchangetest/schain-host-only.json
  openrtb_ext/convert_down.go
  openrtb_ext/convert_down_test.go
Labels: do not port

#3728 ImproveDigital: Remove placementKey & addtlconsent parsing
  adapters/improvedigital/improvedigital.go
  adapters/improvedigital/improvedigitaltest/supplemental/addtl-consent-multi-tilda.json
  adapters/improvedigital/improvedigitaltest/supplemental/addtl-consent.json
  adapters/improvedigital/params_test.go
  static/bidder-params/improvedigital.json
Labels: PBS 3.0

#3558 Update Cookie Sync Chooser Debug Message to match Java
  endpoints/cookie_sync.go
  endpoints/cookie_sync_test.go
  metrics/go_metrics_test.go
  metrics/metrics.go
  metrics/prometheus/prometheus_test.go
  usersync/chooser.go
  usersync/chooser_test.go
Labels: do not port, PBS 3.0

#3620 Rename Blacklisted Apps to Blocked Apps
  config/config.go
  config/config_test.go
  endpoints/events/event.go
  endpoints/openrtb2/amp_auction.go
  endpoints/openrtb2/amp_auction_test.go
  endpoints/openrtb2/auction.go
  endpoints/openrtb2/auction_benchmark_test.go
  endpoints/openrtb2/auction_test.go
  endpoints/openrtb2/sample-requests/blocked/blocked-app.json
  endpoints/openrtb2/test_utils.go
  endpoints/openrtb2/video_auction.go
  endpoints/openrtb2/video_auction_test.go
  errortypes/code.go
  errortypes/errortypes.go
  metrics/config/metrics_test.go
  metrics/metrics.go
  metrics/prometheus/prometheus_test.go
Labels: do not port, PBS 3.0

#4022 Cookie Sync: Use max when limit is 0
  endpoints/cookie_sync.go
  endpoints/cookie_sync_test.go
Labels: do not port, PBS 3.0

#4020 Remove Default Request Hardcoded Aliases
  endpoints/info/bidders.go
  endpoints/info/bidders_detail.go
  endpoints/info/bidders_detail_test.go
  endpoints/info/bidders_test.go
  endpoints/openrtb2/auction.go
  router/router.go
  router/router_test.go
  router/test_aliases.json
Labels: do not port, PBS 3.0
