Repository prebid/prebid-server, pull requests merged in 2025-02, with the labels that each got.

#4069 New Adapter: Bidtheatre
  adapters/bidtheatre/bidtheatre.go
  adapters/bidtheatre/bidtheatre_test.go
  adapters/bidtheatre/bidtheatretest/exemplary/simple-banner.json
  adapters/bidtheatre/bidtheatretest/exemplary/simple-video.json
  adapters/bidtheatre/bidtheatretest/supplemental/bad-bid-type.json
  adapters/bidtheatre/bidtheatretest/supplemental/bad-response-body.json
  adapters/bidtheatre/bidtheatretest/supplemental/status-204.json
  adapters/bidtheatre/bidtheatretest/supplemental/status-400.json
  adapters/bidtheatre/bidtheatretest/supplemental/status-500.json
  adapters/bidtheatre/params_test.go
  exchange/adapter_builders.go
  openrtb_ext/bidders.go
  openrtb_ext/imp_bidtheatre.go
  static/bidder-info/bidtheatre.yaml
  static/bidder-params/bidtheatre.json
Labels: adapter

#4116 New Adapter: 152 Media - Adkernel alias
  static/bidder-info/152media.yaml
Labels: adapter

#4153 Rubicon: Pass imp[].ext.tid
  adapters/rubicon/rubicon.go
  adapters/rubicon/rubicontest/exemplary/flexible-schema.json
Labels: adapter

#4149 New adapter: Connektai - Xeworks alias
  static/bidder-info/connektai.yaml
Labels: adapter

#4093 Compass: Add user sync GPP support
  static/bidder-info/compass.yaml
Labels: adapter

#4113 Adnuntius: Copy advertiserDomains to ORTB bid response adomain
  adapters/adnuntius/adnuntius.go
  adapters/adnuntius/adnuntiustest/exemplary/simple-banner.json
  adapters/adnuntius/adnuntiustest/supplemental/check-dealId.json
  adapters/adnuntius/adnuntiustest/supplemental/check-dsa-advertiser-legalName-omitted.json
  adapters/adnuntius/adnuntiustest/supplemental/check-dsa-advertiser-legalName.json
  adapters/adnuntius/adnuntiustest/supplemental/check-dsa-advertiser-omitted.json
  adapters/adnuntius/adnuntiustest/supplemental/check-gdpr.json
  adapters/adnuntius/adnuntiustest/supplemental/check-gross-bids.json
  adapters/adnuntius/adnuntiustest/supplemental/check-net-bids.json
  adapters/adnuntius/adnuntiustest/supplemental/check-noCookies-parameter.json
  adapters/adnuntius/adnuntiustest/supplemental/check-noCookies.json
  adapters/adnuntius/adnuntiustest/supplemental/check-order-multi-imp.json
  adapters/adnuntius/adnuntiustest/supplemental/check-userId.json
  adapters/adnuntius/adnuntiustest/supplemental/empty-regs-ext.json
  adapters/adnuntius/adnuntiustest/supplemental/empty-regs.json
  adapters/adnuntius/adnuntiustest/supplemental/height-error.json
  adapters/adnuntius/adnuntiustest/supplemental/max-deals-test.json
  adapters/adnuntius/adnuntiustest/supplemental/send-header-information.json
  adapters/adnuntius/adnuntiustest/supplemental/site-ext.json
  adapters/adnuntius/adnuntiustest/supplemental/size-check.json
  adapters/adnuntius/adnuntiustest/supplemental/test-networks.json
  adapters/adnuntius/adnuntiustest/supplemental/user-ext.json
  adapters/adnuntius/adnuntiustest/supplemental/width-error.json
Labels: adapter

#4148 New Adapter: Smoot
  adapters/smoot/params_test.go
  adapters/smoot/smoot.go
  adapters/smoot/smoot_test.go
  adapters/smoot/smoottest/exemplary/endpointId.json
  adapters/smoot/smoottest/exemplary/multi-format.json
  adapters/smoot/smoottest/exemplary/multi-imp.json
  adapters/smoot/smoottest/exemplary/simple-app-banner.json
  adapters/smoot/smoottest/exemplary/simple-native.json
  adapters/smoot/smoottest/exemplary/simple-video.json
  adapters/smoot/smoottest/exemplary/simple-web-banner.json
  adapters/smoot/smoottest/supplemental/bad-media-type.json
  adapters/smoot/smoottest/supplemental/bad-response.json
  adapters/smoot/smoottest/supplemental/invalid-bidder.json
  adapters/smoot/smoottest/supplemental/invalid-ext.json
  adapters/smoot/smoottest/supplemental/status-204.json
  adapters/smoot/smoottest/supplemental/status-not-200.json
  exchange/adapter_builders.go
  openrtb_ext/bidders.go
  openrtb_ext/imp_smoot.go
  static/bidder-info/smoot.yaml
  static/bidder-params/smoot.json
Labels: adapter

#4168 Connatix: Add viewability field
  adapters/connatix/connatix.go
  adapters/connatix/connatixtest/supplemental/success-build-display-manager-version.json
  adapters/connatix/models.go
  openrtb_ext/imp_connatix.go
  static/bidder-params/connatix.json
Labels: adapter

#4191 Copper6SSP: Fix endpoint
  static/bidder-info/copper6ssp.yaml
Labels: adapter

#4190 Pubrise: Fix endpoint
  static/bidder-info/pubrise.yaml
Labels: adapter

#4184 sspBC: Endpoint update
  static/bidder-info/sspBC.yaml
Labels: adapter

#4176 New Adapter: Addigi - Attekmi (SmartHub) Alias
  static/bidder-info/addigi.yaml
Labels: adapter

#4023 New Adapter: Loopme
  adapters/loopme/loopme.go
  adapters/loopme/loopme_test.go
  adapters/loopme/loopmetest/exemplary/app-formats.json
  adapters/loopme/loopmetest/exemplary/app-imps.json
  adapters/loopme/loopmetest/exemplary/no-bid.json
  adapters/loopme/loopmetest/exemplary/no-seat-bid.json
  adapters/loopme/loopmetest/exemplary/no-seat.json
  adapters/loopme/loopmetest/exemplary/simple-app-audio.json
  adapters/loopme/loopmetest/exemplary/simple-app-banner.json
  adapters/loopme/loopmetest/exemplary/simple-app-native.json
  adapters/loopme/loopmetest/exemplary/simple-app-video.json
  adapters/loopme/loopmetest/exemplary/simple-site-audio.json
  adapters/loopme/loopmetest/exemplary/simple-site-banner.json
  adapters/loopme/loopmetest/exemplary/simple-site-native.json
  adapters/loopme/loopmetest/exemplary/simple-site-video.json
  adapters/loopme/loopmetest/supplemental/resp-bad-json.json
  adapters/loopme/loopmetest/supplemental/resp-bad-markuptype.json
  adapters/loopme/loopmetest/supplemental/status-400.json
  adapters/loopme/loopmetest/supplemental/status-500.json
  adapters/loopme/loopmetest/supplemental/status-503.json
  adapters/loopme/params_test.go
  exchange/adapter_builders.go
  openrtb_ext/bidders.go
  openrtb_ext/imp_loopme.go
  static/bidder-info/loopme.yaml
  static/bidder-params/loopme.json
Labels: adapter

#4183 New Adapter: Adt - Admatic alias
  static/bidder-info/adt.yaml
Labels: adapter

#3994 New Adapter: Mediasquare
  adapters/mediasquare/mediasquare.go
  adapters/mediasquare/mediasquare_test.go
  adapters/mediasquare/mediasquaretest/exemplary/multi-format.json
  adapters/mediasquare/mediasquaretest/exemplary/simple-banner.json
  adapters/mediasquare/mediasquaretest/exemplary/simple-native.json
  adapters/mediasquare/mediasquaretest/exemplary/simple-video.json
  adapters/mediasquare/mediasquaretest/supplemental/no-valid-imp-ext.json
  adapters/mediasquare/mediasquaretest/supplemental/no-valid-response.json
  adapters/mediasquare/mediasquaretest/supplemental/status-400.json
  adapters/mediasquare/mediasquaretest/supplemental/status-not-200.json
  adapters/mediasquare/params_test.go
  adapters/mediasquare/parsers.go
  adapters/mediasquare/structs.go
  adapters/mediasquare/utils.go
  exchange/adapter_builders.go
  openrtb_ext/bidders.go
  openrtb_ext/imp_mediasquare.go
  static/bidder-info/mediasquare.yaml
  static/bidder-params/mediasquare.json
Labels: adapter

#3918 Rubicon: Remove imp.ext.context references
  adapters/rubicon/rubicon.go
  adapters/rubicon/rubicon_test.go
  adapters/rubicon/rubicontest/exemplary/app-imp-fpd.json
  adapters/rubicon/rubicontest/exemplary/flexible-schema.json
Labels: do not port, adapter

#4166 Rubicon: Remove pchain support
  adapters/rubicon/rubicon.go
  adapters/rubicon/rubicontest/exemplary/25-26-transition-period.json
  adapters/rubicon/rubicontest/exemplary/simple-banner.json
  openrtb_ext/imp_rubicon.go
Labels: adapter

#4202 RTB House: Declare OpenRTB 2.6 support
  static/bidder-info/rtbhouse.yaml
Labels: adapter

#4204 Undertone: Declare OpenRTB 2.6 support
  static/bidder-info/undertone.yaml
Labels: adapter

#4234 Upgrade to Go 1.24
  .devcontainer/devcontainer.json
  .github/workflows/adapter-code-coverage.yml
  .github/workflows/validate-merge.yml
  .github/workflows/validate.yml
  Dockerfile
  README.md
  go.mod
Labels: do not port

#4199 New Adapter: Jambojar - Attekmi (SmartHub) Alias
  static/bidder-info/jambojar.yaml
Labels: adapter

#4164 New Adapter: Adinify - Attekmi (SmartHub) alias
  static/bidder-info/adinify.yaml
Labels: adapter

#4165 New Adapter: Artechnology - Attekmi (SmartHub) alias
  static/bidder-info/artechnology.yaml
Labels: adapter

#4198 New Adapter: Seedtag
  adapters/seedtag/params_test.go
  adapters/seedtag/seedtag.go
  adapters/seedtag/seedtag_test.go
  adapters/seedtag/seedtagtest/exemplary/banner.json
  adapters/seedtag/seedtagtest/exemplary/bidfloor_converted.json
  adapters/seedtag/seedtagtest/exemplary/video.json
  adapters/seedtag/seedtagtest/supplemental/invalid_bidfloor_conversion.json
  adapters/seedtag/seedtagtest/supplemental/invalid_mtype.json
  adapters/seedtag/seedtagtest/supplemental/response_unmarshal_error.json
  adapters/seedtag/seedtagtest/supplemental/status_bad_request.json
  adapters/seedtag/seedtagtest/supplemental/status_no_content.json
  adapters/seedtag/seedtagtest/supplemental/status_not_ok.json
  exchange/adapter_builders.go
  openrtb_ext/bidders.go
  openrtb_ext/imp_seedtag.go
  static/bidder-info/seedtag.yaml
  static/bidder-params/seedtag.json
Labels: adapter
